# Generated by Django 3.2.18 on 2023-08-09 13:37

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0015_set_managed_to_true_in_all_models'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='insuree',
            name='insuree_wallet',
            field=models.CharField(blank=True, db_column='Insuree_Wallet', max_length=50, null=True),
        ),
        
    ]