# Generated by Django 3.2.16 on 2023-10-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0015_set_managed_to_true_in_all_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='chf_id',
            field=models.CharField(blank=True, db_column='CHFID', max_length=40, null=True),
        ),
    ]
