# Generated by Django 3.2.16 on 2024-02-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0016_auto_20230809_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='is_pregnant',
            field=models.BooleanField(blank=True, db_column='IsPregnant', null=True),
        ),
    ]
