# Generated by Django 3.2.16 on 2024-02-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0017_insuree_is_pregnant'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='is_formal_sector',
            field=models.BooleanField(blank=True, db_column='IsFormalSector', null=True),
        ),
    ]
