# Generated by Django 3.2.19 on 2023-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0018_remove_insuree_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='is_local',
            field=models.BooleanField(blank=True, db_column='IsLocal', max_length=100, null=True),
        ),
    ]
