# Generated by Django 3.2.19 on 2023-06-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0020_alter_insuree_is_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='residential_house_number',
            field=models.BigIntegerField(blank=True, db_column='ResidentialHouseNumber', max_length=100, null=True),
        ),
    ]
