# Generated by Django 3.2.19 on 2023-06-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0022_alter_insuree_residential_house_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuree',
            name='residential_house_number',
        ),
        migrations.AddField(
            model_name='insuree',
            name='house_number',
            field=models.CharField(blank=True, db_column='HouseNumber', max_length=100, null=True),
        ),
    ]
