# Generated by Django 3.2.19 on 2023-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0024_herautilities_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='herautilities',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='herautilities',
            name='policy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
